### ISSUE TITLE
[BUG] Repeating ID button

### ISSUE THREAD

**Issue by sy-python** [lensvol/fl-identica#3]
Repeating ID button

#### Issue description
When using this extension along with Fallen London Favourites extension, storylets that are pinned to the top or the bottom get an extra info button.

#### Steps to reproduce the issue
1. Install Fallen London Favourites extension and FL Identica extension
2. Pin a storylet to the top or the bottom
3. Exit the location and enter back

#### What's the expected result?
One (i) button on the pinned storylet

#### What's the actual result?
Two (i) buttons on the pinned storylet

See attached screenshot for additional details

![bug1](https://user-images.githubusercontent.com/40476927/182866433-1cea5e9f-04a1-44cb-aa89-fda832820cd2.PNG)

**Comment by lensvol** [comment]
Thank you, I will take a look.

**Comment by SansCipher** [comment]
Apparently the buttons are added every time I discard or draw which gets funnier. Gonna be using previous version until fix
![bug2](https://user-images.githubusercontent.com/40476927/182871442-5103d43a-4a7a-4a8f-a1bc-507efe9c357b.PNG)

**Comment by lensvol** [comment]
Fixed in 71e8ad458665228b1e1033700bd8951375377879.

**Comment by SansCipher** [comment]
Fix didn't work, still experiencing bug after updating to 1.1.1
![image](https://user-images.githubusercontent.com/40476927/182978990-ffa1ae29-0f39-4261-a621-ec214789e3d8.png)

**Comment by lensvol** [comment]
That's a different case, but it is related. I'll need time to reproduce it.
